name: Autograding Tests
on: 
  push:
    branches:
      - main
    # paths-ignore:
    #   - '.github/**'
env:
  IMG_URL_riscv64: https://github.com/Azure-stars/testsuits-for-oskernel/releases/download/v0.1/sdcard-riscv64.img.gz # 镜像url
  IMG_URL_loongarch64: https://github.com/Azure-stars/testsuits-for-oskernel/releases/download/v0.1/sdcard-loongarch64.img.gz # 镜像url
  IMG_URL_aarch64: https://github.com/Azure-stars/testsuits-for-oskernel/releases/download/v0.1/sdcard-aarch64.img.gz # 镜像url
  IMG_URL_x86_64: https://github.com/Azure-stars/testsuits-for-oskernel/releases/download/v0.1/sdcard-x86_64.img.gz # 镜像url
  TIMEOUT: 300 # 超时时间
  SCRIPT_REPO: https://github.com/oscontent25/EvaluationScript # 脚本仓库
 
jobs:  
  run-autograding-tests:
    runs-on: ubuntu-latest
    env:
      qemu-version: 9.2.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2025-01-18
          components: rust-src, llvm-tools
          targets: x86_64-unknown-none, riscv64gc-unknown-none-elf, aarch64-unknown-none, aarch64-unknown-none-softfloat, loongarch64-unknown-none
      - uses: Swatinem/rust-cache@v2
      - run: cargo install cargo-binutils
      - uses: ./.github/workflows/setup-musl
        with:
          arch: riscv64
      - uses: ./.github/workflows/setup-musl
        with:
          arch: loongarch64
      - uses: ./.github/workflows/setup-musl
        with:
          arch: aarch64
      - uses: ./.github/workflows/setup-musl
        with:
          arch: x86_64
      - uses: ./.github/workflows/setup-qemu
        with:
          qemu-version: ${{ env.qemu-version }}
      - name: Build python environment
        run: sudo apt-get install -y python3 python3-pip
      - name: build os.bin
        run: |
          touch riscv64_output.txt
          touch loongarch64_output.txt
          touch aarch64_output.txt
          touch x86_64_output.txt
          make oscomp_run ARCH=riscv64 BLK=y NET=y FEATURES=fp_simd,lwext4_rs > riscv64_output.txt || true
          make clean
          make oscomp_run ARCH=loongarch64 BLK=y NET=y FEATURES=fp_simd,lwext4_rs > loongarch64_output.txt || true
          make clean
          make oscomp_run ARCH=aarch64 BLK=y NET=y FEATURES=fp_simd,lwext4_rs > aarch64_output.txt || true
          make clean
          make oscomp_run ARCH=x86_64 BLK=y NET=y FEATURES=fp_simd,lwext4_rs ACCEL=n > x86_64_output.txt || true

      - name: Download EvaluationScript
        run: |
            git clone ${{ env.SCRIPT_REPO }} .github/classroom

      - name: riscvglibcbasic-test
        uses: oscontent25/os-autograding@master
        id: riscvglibcbasic
        with:
          outputfile: riscv64_output.txt
          scriptPath: .github/classroom/glibc-basic
      - name: loongarchglibcbasic-test
        uses: oscontent25/os-autograding@master
        id: loongarchglibcbasic
        with:
          outputfile: loongarch64_output.txt
          scriptPath: .github/classroom/glibc-basic
      - name: aarchglibcbasic-test
        uses: oscontent25/os-autograding@master
        id: aarchglibcbasic
        with:
          outputfile: aarch64_output.txt
          scriptPath: .github/classroom/glibc-basic
      - name: x86glibcbasic-test
        uses: oscontent25/os-autograding@master
        id: x86glibcbasic
        with:
          outputfile: x86_64_output.txt
          scriptPath: .github/classroom/glibc-basic
      - name: riscvglibclibctest-test
        uses: oscontent25/os-autograding@master
        id: riscvglibclibctest
        with:
          outputfile: riscv64_output.txt
          scriptPath: .github/classroom/glibc-libctest
      - name: loongarchglibclibctest-test
        uses: oscontent25/os-autograding@master
        id: loongarchglibclibctest
        with:
          outputfile: loongarch64_output.txt
          scriptPath: .github/classroom/glibc-libctest
      - name: aarchglibclibctest-test
        uses: oscontent25/os-autograding@master
        id: aarchglibclibctest
        with:
          outputfile: aarch64_output.txt
          scriptPath: .github/classroom/glibc-libctest
      - name: x86glibclibctest-test
        uses: oscontent25/os-autograding@master
        id: x86glibclibctest
        with:
          outputfile: x86_64_output.txt
          scriptPath: .github/classroom/glibc-libctest
      - name: riscvglibclua-test
        uses: oscontent25/os-autograding@master
        id: riscvglibclua
        with:
          outputfile: riscv64_output.txt
          scriptPath: .github/classroom/glibc-lua
      - name: loongarchglibclua-test
        uses: oscontent25/os-autograding@master
        id: loongarchglibclua
        with:
          outputfile: loongarch64_output.txt
          scriptPath: .github/classroom/glibc-lua
      - name: aarchglibclua-test
        uses: oscontent25/os-autograding@master
        id: aarchglibclua
        with:
          outputfile: aarch64_output.txt
          scriptPath: .github/classroom/glibc-lua
      - name: x86glibclua-test
        uses: oscontent25/os-autograding@master
        id: x86glibclua
        with:
          outputfile: x86_64_output.txt
          scriptPath: .github/classroom/glibc-lua
      - name: riscvglibcbusybox-test
        uses: oscontent25/os-autograding@master
        id: riscvglibcbusybox
        with:
          outputfile: riscv64_output.txt
          scriptPath: .github/classroom/glibc-busybox
      - name: loongarchglibcbusybox-test
        uses: oscontent25/os-autograding@master
        id: loongarchglibcbusybox
        with:
          outputfile: loongarch64_output.txt
          scriptPath: .github/classroom/glibc-busybox
      - name: aarchglibcbusybox-test
        uses: oscontent25/os-autograding@master
        id: aarchglibcbusybox
        with:
          outputfile: aarch64_output.txt
          scriptPath: .github/classroom/glibc-busybox
      - name: x86glibcbusybox-test
        uses: oscontent25/os-autograding@master
        id: x86glibcbusybox
        with:
          outputfile: x86_64_output.txt
          scriptPath: .github/classroom/glibc-busybox
      - name: riscvglibciozone-test
        uses: oscontent25/os-autograding@master
        id: riscvglibciozone
        with:
          outputfile: riscv64_output.txt
          scriptPath: .github/classroom/glibc-iozone
      - name: loongarchglibciozone-test
        uses: oscontent25/os-autograding@master
        id: loongarchglibciozone
        with:
          outputfile: loongarch64_output.txt
          scriptPath: .github/classroom/glibc-iozone
      - name: aarchglibciozone-test
        uses: oscontent25/os-autograding@master
        id: aarchglibciozone
        with:
          outputfile: aarch64_output.txt
          scriptPath: .github/classroom/glibc-iozone
      - name: x86glibciozone-test
        uses: oscontent25/os-autograding@master
        id: x86glibciozone
        with:
          outputfile: x86_64_output.txt
          scriptPath: .github/classroom/glibc-iozone
      - name: riscvmuslbasic-test
        uses: oscontent25/os-autograding@master
        id: riscvmuslbasic
        with:
          outputfile: riscv64_output.txt
          scriptPath: .github/classroom/musl-basic
      - name: loongarchmuslbasic-test
        uses: oscontent25/os-autograding@master
        id: loongarchmuslbasic
        with:
          outputfile: loongarch64_output.txt
          scriptPath: .github/classroom/musl-basic
      - name: aarchmuslbasic-test
        uses: oscontent25/os-autograding@master
        id: aarchmuslbasic
        with:
          outputfile: aarch64_output.txt
          scriptPath: .github/classroom/musl-basic
      - name: x86muslbasic-test
        uses: oscontent25/os-autograding@master
        id: x86muslbasic
        with:
          outputfile: x86_64_output.txt
          scriptPath: .github/classroom/musl-basic
      - name: riscvmusllibctest-test
        uses: oscontent25/os-autograding@master
        id: riscvmusllibctest
        with:
          outputfile: riscv64_output.txt
          scriptPath: .github/classroom/musl-libctest
      - name: loongarchmusllibctest-test
        uses: oscontent25/os-autograding@master
        id: loongarchmusllibctest
        with:
          outputfile: loongarch64_output.txt
          scriptPath: .github/classroom/musl-libctest
      - name: aarchmusllibctest-test
        uses: oscontent25/os-autograding@master
        id: aarchmusllibctest
        with:
          outputfile: aarch64_output.txt
          scriptPath: .github/classroom/musl-libctest
      - name: x86musllibctest-test
        uses: oscontent25/os-autograding@master
        id: x86musllibctest
        with:
          outputfile: x86_64_output.txt
          scriptPath: .github/classroom/musl-libctest
      - name: riscvmusllua-test
        uses: oscontent25/os-autograding@master
        id: riscvmusllua
        with:
          outputfile: riscv64_output.txt
          scriptPath: .github/classroom/musl-lua
      - name: loongarchmusllua-test
        uses: oscontent25/os-autograding@master
        id: loongarchmusllua
        with:
          outputfile: loongarch64_output.txt
          scriptPath: .github/classroom/musl-lua
      - name: aarchmusllua-test
        uses: oscontent25/os-autograding@master
        id: aarchmusllua
        with:
          outputfile: aarch64_output.txt
          scriptPath: .github/classroom/musl-lua
      - name: x86musllua-test
        uses: oscontent25/os-autograding@master
        id: x86musllua
        with:
          outputfile: x86_64_output.txt
          scriptPath: .github/classroom/musl-lua
      - name: riscvmuslbusybox-test
        uses: oscontent25/os-autograding@master
        id: riscvmuslbusybox
        with:
          outputfile: riscv64_output.txt
          scriptPath: .github/classroom/musl-busybox
      - name: loongarchmuslbusybox-test
        uses: oscontent25/os-autograding@master
        id: loongarchmuslbusybox
        with:
          outputfile: loongarch64_output.txt
          scriptPath: .github/classroom/musl-busybox
      - name: aarchmuslbusybox-test
        uses: oscontent25/os-autograding@master
        id: aarchmuslbusybox
        with:
          outputfile: aarch64_output.txt
          scriptPath: .github/classroom/musl-busybox
      - name: x86muslbusybox-test
        uses: oscontent25/os-autograding@master
        id: x86muslbusybox
        with:
          outputfile: x86_64_output.txt
          scriptPath: .github/classroom/musl-busybox
      - name: riscvmusliozone-test
        uses: oscontent25/os-autograding@master
        id: riscvmusliozone
        with:
          outputfile: riscv64_output.txt
          scriptPath: .github/classroom/musl-iozone
      - name: loongarchmusliozone-test
        uses: oscontent25/os-autograding@master
        id: loongarchmusliozone
        with:
          outputfile: loongarch64_output.txt
          scriptPath: .github/classroom/musl-iozone
      - name: aarchmusliozone-test
        uses: oscontent25/os-autograding@master
        id: aarchmusliozone
        with:
          outputfile: aarch64_output.txt
          scriptPath: .github/classroom/musl-iozone
      - name: x86musliozone-test
        uses: oscontent25/os-autograding@master
        id: x86musliozone
        with:
          outputfile: x86_64_output.txt
          scriptPath: .github/classroom/musl-iozone
      
      - name: Autograding Reporter
        uses: oscontent25/autograding-grading-reporter@v1
        env:
          RISCVGLIBCBASIC_RESULTS: "${{steps.riscvglibcbasic.outputs.result}}"
          LOONGARCHGLIBCBASIC_RESULTS: "${{steps.loongarchglibcbasic.outputs.result}}"
          AARCHGLIBCBASIC_RESULTS: "${{steps.aarchglibcbasic.outputs.result}}"
          X86GLIBCBASIC_RESULTS: "${{steps.x86glibcbasic.outputs.result}}"
          RISCVGLIBCLIBCTEST_RESULTS: "${{steps.riscvglibclibctest.outputs.result}}"
          LOONGARCHGLIBCLIBCTEST_RESULTS: "${{steps.loongarchglibclibctest.outputs.result}}"
          AARCHGLIBCLIBCTEST_RESULTS: "${{steps.aarchglibclibctest.outputs.result}}"
          X86GLIBCLIBCTEST_RESULTS: "${{steps.x86glibclibctest.outputs.result}}"
          RISCVGLIBCLUA_RESULTS: "${{steps.riscvglibclua.outputs.result}}"
          LOONGARCHGLIBCLUA_RESULTS: "${{steps.loongarchglibclua.outputs.result}}"
          AARCHGLIBCLUA_RESULTS: "${{steps.aarchglibclua.outputs.result}}"
          X86GLIBCLUA_RESULTS: "${{steps.x86glibclua.outputs.result}}"
          RISCVGLIBCBUSYBOX_RESULTS: "${{steps.riscvglibcbusybox.outputs.result}}"
          LOONGARCHGLIBCBUSYBOX_RESULTS: "${{steps.loongarchglibcbusybox.outputs.result}}"
          AARCHGLIBCBUSYBOX_RESULTS: "${{steps.aarchglibcbusybox.outputs.result}}"
          X86GLIBCBUSYBOX_RESULTS: "${{steps.x86glibcbusybox.outputs.result}}"
          RISCVGLIBCIOZONE_RESULTS: "${{steps.riscvglibciozone.outputs.result}}"
          LOONGARCHGLIBCIOZONE_RESULTS: "${{steps.loongarchglibciozone.outputs.result}}"
          AARCHGLIBCIOZONE_RESULTS: "${{steps.aarchglibciozone.outputs.result}}"
          X86GLIBCIOZONE_RESULTS: "${{steps.x86glibciozone.outputs.result}}"
          RISCVMUSLBASIC_RESULTS: "${{steps.riscvmuslbasic.outputs.result}}"
          LOONGARCHMUSLBASIC_RESULTS: "${{steps.loongarchmuslbasic.outputs.result}}"
          AARCHMUSLBASIC_RESULTS: "${{steps.aarchmuslbasic.outputs.result}}"
          X86MUSLBASIC_RESULTS: "${{steps.x86muslbasic.outputs.result}}"
          RISCVMUSLLIBCTEST_RESULTS: "${{steps.riscvmusllibctest.outputs.result}}"
          LOONGARCHMUSLLIBCTEST_RESULTS: "${{steps.loongarchmusllibctest.outputs.result}}"
          AARCHMUSLLIBCTEST_RESULTS: "${{steps.aarchmusllibctest.outputs.result}}"
          X86MUSLLIBCTEST_RESULTS: "${{steps.x86musllibctest.outputs.result}}"
          RISCVMUSLLUA_RESULTS: "${{steps.riscvmusllua.outputs.result}}"
          LOONGARCHMUSLLUA_RESULTS: "${{steps.loongarchmusllua.outputs.result}}"
          AARCHMUSLLUA_RESULTS: "${{steps.aarchmusllua.outputs.result}}"
          X86MUSLLUA_RESULTS: "${{steps.x86musllua.outputs.result}}"
          RISCVMUSLBUSYBOX_RESULTS: "${{steps.riscvmuslbusybox.outputs.result}}"
          LOONGARCHMUSLBUSYBOX_RESULTS: "${{steps.loongarchmuslbusybox.outputs.result}}"
          AARCHMUSLBUSYBOX_RESULTS: "${{steps.aarchmuslbusybox.outputs.result}}"
          X86MUSLBUSYBOX_RESULTS: "${{steps.x86muslbusybox.outputs.result}}"
          RISCVMUSLIOZONE_RESULTS: "${{steps.riscvmusliozone.outputs.result}}"
          LOONGARCHMUSLIOZONE_RESULTS: "${{steps.loongarchmusliozone.outputs.result}}"
          AARCHMUSLIOZONE_RESULTS: "${{steps.aarchmusliozone.outputs.result}}"
          X86MUSLIOZONE_RESULTS: "${{steps.x86musliozone.outputs.result}}"
        with:
          runners: riscvglibcbasic,loongarchglibcbasic,aarchglibcbasic,x86glibcbasic,riscvglibclibctest,loongarchglibclibctest,aarchglibclibctest,x86glibclibctest,riscvglibclua,loongarchglibclua,aarchglibclua,x86glibclua,riscvglibcbusybox,loongarchglibcbusybox,aarchglibcbusybox,x86glibcbusybox,riscvglibciozone,loongarchglibciozone,aarchglibciozone,x86glibciozone,riscvmuslbasic,loongarchmuslbasic,aarchmuslbasic,x86muslbasic,riscvmusllibctest,loongarchmusllibctest,aarchmusllibctest,x86musllibctest,riscvmusllua,loongarchmusllua,aarchmusllua,x86musllua,riscvmuslbusybox,loongarchmuslbusybox,aarchmuslbusybox,x86muslbusybox,riscvmusliozone,loongarchmusliozone,aarchmusliozone,x86musliozone
          token: ${{ secrets.GITHUB_TOKEN }}

        
